name: 'CodeLayers PR Visualization'
description: 'Generate a 3D code visualization for your PR and post a comment with the share link'
author: 'CodeLayers'

branding:
  icon: 'eye'
  color: 'purple'

inputs:
  api_key:
    description: 'CodeLayers API key (from `codelayers api-keys create`)'
    required: true
  base_branch:
    description: 'Base branch to compare against (default: auto-detect from PR)'
    required: false
    default: ''
  expires_days:
    description: 'Days until the share link expires'
    required: false
    default: '7'
  max_views:
    description: 'Maximum number of views (empty = unlimited)'
    required: false
    default: ''
  comment:
    description: 'Post/update a PR comment with the share link'
    required: false
    default: 'true'
  link_to_pr:
    description: 'Link share to GitHub repo/PR metadata (stores repo name + PR number)'
    required: false
    default: 'true'

outputs:
  share_url:
    description: 'Full share URL with encryption key'
  share_id:
    description: 'Share ID (UUID)'
  node_count:
    description: 'Number of nodes in the graph'
  changed_file_count:
    description: 'Number of files changed in the PR'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/codelayers-ai/codelayers-cli:latest'
  env:
    CODELAYERS_API_KEY: ${{ inputs.api_key }}
    GITHUB_TOKEN: ${{ github.token }}
