name: 'CodeLayers PR Visualization'
description: 'Generate a 3D code visualization for your PR and post a comment with the share link'
author: 'CodeLayers'

branding:
  icon: 'eye'
  color: 'purple'

inputs:
  api_key:
    description: 'CodeLayers API key (from `codelayers api-keys create`)'
    required: true
  base_branch:
    description: 'Base branch to compare against (default: auto-detect from PR)'
    required: false
    default: ''
  expires_days:
    description: 'Days until the share link expires'
    required: false
    default: '7'
  max_views:
    description: 'Maximum number of views (empty = unlimited)'
    required: false
    default: ''
  comment:
    description: 'Post/update a PR comment with the share link'
    required: false
    default: 'true'
  link_to_pr:
    description: 'Link share to GitHub repo/PR metadata (stores repo name + PR number)'
    required: false
    default: 'true'
  api_url:
    description: 'CodeLayers API URL (override for self-hosted)'
    required: false
    default: 'https://api.codelayers.ai'
  cli_image:
    description: 'CLI Docker image to use'
    required: false
    default: 'ghcr.io/codelayers-ai/codelayers-cli:latest'

outputs:
  share_url:
    description: 'Full share URL with encryption key'
  share_id:
    description: 'Share ID (UUID)'
  node_count:
    description: 'Number of nodes in the graph'
  changed_file_count:
    description: 'Number of files changed in the PR'

runs:
  using: 'composite'
  steps:
    - name: Detect base branch
      id: base
      shell: bash
      run: |
        if [ -n "${{ inputs.base_branch }}" ]; then
          echo "ref=${{ inputs.base_branch }}" >> "$GITHUB_OUTPUT"
        elif [ -n "${{ github.event.pull_request.base.ref }}" ]; then
          echo "ref=origin/${{ github.event.pull_request.base.ref }}" >> "$GITHUB_OUTPUT"
        else
          echo "ref=origin/main" >> "$GITHUB_OUTPUT"
        fi

    - name: Fetch base branch
      shell: bash
      run: |
        git fetch origin "${{ github.event.pull_request.base.ref || 'main' }}" --depth=1

    - name: Parse and create share
      id: share
      shell: bash
      env:
        CODELAYERS_API_KEY: ${{ inputs.api_key }}
        CODELAYERS_API_URL: ${{ inputs.api_url }}
      run: |
        # Build share CLI args
        SHARE_ARGS="share /workspace --base ${{ steps.base.outputs.ref }} --head HEAD --format json --expires ${{ inputs.expires_days }}"

        if [ -n "${{ inputs.max_views }}" ]; then
          SHARE_ARGS="$SHARE_ARGS --max-views ${{ inputs.max_views }}"
        fi

        if [ "${{ inputs.link_to_pr }}" = "true" ]; then
          SHARE_ARGS="$SHARE_ARGS --github-repo ${{ github.repository }}"
          if [ -n "${{ github.event.pull_request.number }}" ]; then
            SHARE_ARGS="$SHARE_ARGS --github-pr ${{ github.event.pull_request.number }}"
            SHARE_ARGS="$SHARE_ARGS --github-pr-title \"${{ github.event.pull_request.title }}\""
          fi
        fi

        echo "Running: codelayers $SHARE_ARGS"

        # Share command now parses on-the-fly (no sync needed)
        RESULT=$(docker run --rm \
          -v "${{ github.workspace }}:/workspace" \
          -e CODELAYERS_API_KEY \
          -e CODELAYERS_API_URL \
          -e HOME=/tmp \
          "${{ inputs.cli_image }}" \
          $SHARE_ARGS)

        echo "CLI output: $RESULT"

        # Parse JSON output (last line of output is the JSON)
        JSON_LINE=$(echo "$RESULT" | grep -E '^\{' | tail -1)
        SHARE_URL=$(echo "$JSON_LINE" | jq -r '.share_url')
        SHARE_ID=$(echo "$JSON_LINE" | jq -r '.share_id')
        NODE_COUNT=$(echo "$JSON_LINE" | jq -r '.node_count')
        CHANGED_FILE_COUNT=$(echo "$JSON_LINE" | jq -r '.changed_file_count')

        # Set outputs
        echo "share_url=$SHARE_URL" >> "$GITHUB_OUTPUT"
        echo "share_id=$SHARE_ID" >> "$GITHUB_OUTPUT"
        echo "node_count=$NODE_COUNT" >> "$GITHUB_OUTPUT"
        echo "changed_file_count=$CHANGED_FILE_COUNT" >> "$GITHUB_OUTPUT"

    - name: Post PR comment
      if: inputs.comment == 'true' && github.event.pull_request.number
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        SHARE_URL="${{ steps.share.outputs.share_url }}"
        NODE_COUNT="${{ steps.share.outputs.node_count }}"
        CHANGED="${{ steps.share.outputs.changed_file_count }}"

        COMMENT_BODY="## CodeLayers 3D Visualization

        | Metric | Value |
        |--------|-------|
        | Graph nodes | $NODE_COUNT |
        | Changed files | $CHANGED |
        | Expires | ${{ inputs.expires_days }} days |

        [**Open 3D Visualization**]($SHARE_URL)

        <sub>Generated by [CodeLayers Action](https://github.com/codelayers-ai/codelayers-action)</sub>"

        # Find existing CodeLayers comment
        COMMENT_ID=$(gh api \
          repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
          --jq '.[] | select(.body | contains("CodeLayers 3D Visualization")) | .id' \
          2>/dev/null | head -1)

        if [ -n "$COMMENT_ID" ]; then
          # Update existing comment
          gh api \
            repos/${{ github.repository }}/issues/comments/$COMMENT_ID \
            -X PATCH \
            -f body="$COMMENT_BODY"
          echo "Updated existing PR comment"
        else
          # Create new comment
          gh pr comment ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --body "$COMMENT_BODY"
          echo "Created new PR comment"
        fi
