name: 'CodeLayers PR Visualization'
description: 'Generate a 3D code visualization for your PR. Free for public repos, API key required for private repos.'
author: 'CodeLayers'

branding:
  icon: 'layers'
  color: 'purple'

inputs:
  api_key:
    description: 'CodeLayers API key. Optional for public repos (uses free explore). Required for private repos.'
    required: false
    default: ''
  base_branch:
    description: 'Base branch to compare against (default: auto-detect from PR)'
    required: false
    default: ''
  expires_days:
    description: 'Days until the visualization link expires'
    required: false
    default: '7'
  max_views:
    description: 'Maximum number of views (empty = unlimited, share mode only)'
    required: false
    default: ''
  comment:
    description: 'Post/update a PR comment with the visualization link'
    required: false
    default: 'true'
  link_to_pr:
    description: 'Link share to GitHub repo/PR metadata (stores repo name + PR number)'
    required: false
    default: 'true'

outputs:
  share_url:
    description: 'Full visualization URL (share URL with encryption key, or explore URL)'
  share_id:
    description: 'Share or explore ID (UUID)'
  node_count:
    description: 'Number of nodes in the graph'
  changed_file_count:
    description: 'Number of files changed in the PR'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/codelayers-ai/codelayers-cli:latest'
  env:
    CODELAYERS_API_KEY: ${{ inputs.api_key }}
    GITHUB_TOKEN: ${{ github.token }}
