#!/bin/bash
set -euo pipefail

# --- Detect base branch ---
if [ -n "${INPUT_BASE_BRANCH:-}" ]; then
  BASE_REF="$INPUT_BASE_BRANCH"
else
  # Read from GitHub event payload
  BASE_REF=$(jq -r '.pull_request.base.ref // empty' "$GITHUB_EVENT_PATH" 2>/dev/null || true)
  if [ -n "$BASE_REF" ]; then
    BASE_REF="origin/$BASE_REF"
  else
    BASE_REF="origin/main"
  fi
fi

# --- Fetch base branch ---
FETCH_REF=$(jq -r '.pull_request.base.ref // "main"' "$GITHUB_EVENT_PATH" 2>/dev/null || echo "main")
git fetch origin "$FETCH_REF" --depth=1

# --- Build CLI args ---
ARGS=(share "$GITHUB_WORKSPACE"
  --base "$BASE_REF"
  --head HEAD
  --format json
  --expires "${INPUT_EXPIRES_DAYS:-7}"
)

if [ -n "${INPUT_MAX_VIEWS:-}" ]; then
  ARGS+=(--max-views "$INPUT_MAX_VIEWS")
fi

if [ "${INPUT_LINK_TO_PR:-true}" = "true" ]; then
  ARGS+=(--github-repo "$GITHUB_REPOSITORY")

  PR_NUMBER=$(jq -r '.pull_request.number // empty' "$GITHUB_EVENT_PATH" 2>/dev/null || true)
  if [ -n "$PR_NUMBER" ]; then
    ARGS+=(--github-pr "$PR_NUMBER")
  fi

  PR_TITLE=$(jq -r '.pull_request.title // empty' "$GITHUB_EVENT_PATH" 2>/dev/null || true)
  if [ -n "$PR_TITLE" ]; then
    ARGS+=(--github-pr-title "$PR_TITLE")
  fi
fi

echo "Running: codelayers ${ARGS[*]}"

# --- Run CLI ---
RESULT=$(codelayers "${ARGS[@]}")
echo "CLI output: $RESULT"

# --- Parse JSON output ---
JSON_LINE=$(echo "$RESULT" | grep -E '^\{' | tail -1)
SHARE_URL=$(echo "$JSON_LINE" | jq -r '.share_url')
SHARE_ID=$(echo "$JSON_LINE" | jq -r '.share_id')
NODE_COUNT=$(echo "$JSON_LINE" | jq -r '.node_count')
CHANGED_FILE_COUNT=$(echo "$JSON_LINE" | jq -r '.changed_file_count')

echo "share_url=$SHARE_URL" >> "$GITHUB_OUTPUT"
echo "share_id=$SHARE_ID" >> "$GITHUB_OUTPUT"
echo "node_count=$NODE_COUNT" >> "$GITHUB_OUTPUT"
echo "changed_file_count=$CHANGED_FILE_COUNT" >> "$GITHUB_OUTPUT"

# --- Post PR comment ---
if [ "${INPUT_COMMENT:-true}" != "true" ]; then
  exit 0
fi

PR_NUMBER=$(jq -r '.pull_request.number // empty' "$GITHUB_EVENT_PATH" 2>/dev/null || true)
if [ -z "$PR_NUMBER" ]; then
  exit 0
fi

COMMENT_BODY=$(cat <<EOF
## CodeLayers 3D Visualization

| Metric | Value |
|--------|-------|
| Graph nodes | $NODE_COUNT |
| Changed files | $CHANGED_FILE_COUNT |
| Expires | ${INPUT_EXPIRES_DAYS:-7} days |

[**Open 3D Visualization**]($SHARE_URL)

<sub>Generated by [CodeLayers Action](https://github.com/codelayers-ai/codelayers-action)</sub>
EOF
)

# Find existing comment to update (idempotent)
EXISTING_ID=$(curl -sf \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" \
  | jq -r '.[] | select(.body | contains("CodeLayers 3D Visualization")) | .id' \
  | head -1 || true)

PAYLOAD=$(jq -n --arg body "$COMMENT_BODY" '{body: $body}')

if [ -n "$EXISTING_ID" ]; then
  curl -sf \
    -X PATCH \
    -H "Authorization: token $GITHUB_TOKEN" \
    -H "Accept: application/vnd.github.v3+json" \
    "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/comments/$EXISTING_ID" \
    -d "$PAYLOAD" > /dev/null
  echo "Updated existing PR comment"
else
  curl -sf \
    -X POST \
    -H "Authorization: token $GITHUB_TOKEN" \
    -H "Accept: application/vnd.github.v3+json" \
    "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" \
    -d "$PAYLOAD" > /dev/null
  echo "Created new PR comment"
fi
